packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@iconify/json': ^2.2.402
  '@iconify/tailwind4': ^1.0.6
  '@tailwindcss/vite': ^4.1.16
  '@tsconfig/node22': ^22.0.2
  '@types/node': 22.18.13
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^14.0.0
  commitizen: ^4.3.1
  commitlint: ^20.1.0
  cz-git: ^1.12.0
  eslint: 9.39.0
  husky: ^9.1.7
  jiti: ^2.4.2
  lint-staged: ^16.2.6
  npm-run-all2: ^8.0.4
  tailwindcss: 4.1.16
  typescript: 5.8.3
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^30.0.0
  vite: ^7.0.6
  vue: ^3.5.18
  vue-tsc: ^3.0.4
